### PR TITLE
Bumped to new version 2.3.1.2 and added .gitignore

### PR DESCRIPTION
**Pull request by maxcreation**
I'm willing to take over maintenance if you show me how to publish and maintain the npm package.

### CODE REVIEW

**Comment by maxcreation** [comment]
This has problems. There are new icon files and the gulp tasks would need some updates. I will try to get it working and then open new PR.

**Comment by maxcreation** [comment]
The problem was that there were new icons brands-icons.* and outlined-icons.*. I had to update one gulp task. I think I have solved all the problems. You can now pull my work if you like.

I also changed author and contributor. I didn't mean to be rude, but on my repository, I wanted to change that. When you pull, you can ignore that part.

I'm also willing to be package manager in npm for that and maintain this in future. I would keep npm package name, but you can redirect your GH to my GH when you think it's right.

**Comment by joshmanders** [comment]
Hey @maxcreation thanks for the PR and stepping up to maintain. If you give me your npm username I can add you to the package for publishing, and give you access to the repo.

**Review by joshmanders — CHANGES_REQUESTED** [review]
If you could just put the repository and author back to original but leave your own name in contributors then I can merge it.

**Comment by maxcreation** [comment]
There you go.

**Review by joshmanders — APPROVED** [review]

**Comment by joshmanders** [comment]
Merged and made you an admin of the repo, @maxcreation. Just need your npm username and I can add you to access to that too.

**Comment by maxcreation** [comment]
I created npmjs account. My username is "maxcreation".

**Comment by joshmanders** [comment]
Added you as a maintainer, to publish just make sure that the version of this is the same as the version of semantic. Then just create a commit bumping the version in `package.json`, then tag off that commit, like `git tag 2.3.1` push that up, create a release off that tag linking to the release info of that version of Semantic, and then run `npm publish` to push to npm.

Or take control and do as you please. If you want to change the repo and how it builds go ahead, you're in charge of it.

Thanks for stepping up. If you need any guidance just let me know.

**Pull request merged**
