### PR TITLE
upgrade to SUI 2.4.0

### PR DESCRIPTION
**Pull request by binkydog**
@joshmanders @maxcreation 

Hi, we use this repo in conjunction with `semantic-ui-react` (which is compatible with SUI 2.4.0, and has been for 6 months...) and we'd like to get this up to date.

I did the following to create this:
1. Ran `yarn update gulp` as gulp was using a older dep that was throwing an error.
2. Ran `yarn build` and `yarn test` to build and test files from the 2.4.0-compatible ruby version
3. Updated version in package.json and tagged it to `2.4.0`

I've done some cursory, manual testing with the latest `semantic-ui-react` and it looks pretty good as far as I can tell, including a new 2.4.0 feature (the clearable dropdown style now works).

I was wondering if you'd be willing to either accept this PR (or create one yourself if you prefer) and publish it so we can get it up to SUI 2.4.0.  If that's not in the cards, let me know and we'll use my fork or something else.

Thanks

### CODE REVIEW

**Comment by joshmanders** [comment]
Hey @binkydog thanks for the PR. I will look over the PR this weekend and hopefully get it merged in. Since you are utilizing the package, would you be interested in maintaining it? if so I can add you to both the repo and package to publish.

**Review by joshmanders — APPROVED** [review]

**Comment by joshmanders** [comment]
The 54 file change wasn't as daunting as I was thinking. Merged and published @binkydog. Offer of maintenance stands if you'd like.

**Comment by binkydog** [comment]
Thanks @joshmanders. Yeah, I don't mind pitching in on maintenance... I might want to add a co-worker or two as well so we have can cover it better.

**Comment by joshmanders** [comment]
@binkydog cool. Added you to the repo, if you got an npm account let me know and I'll give you publishing rights.

**Comment by binkydog** [comment]
Thanks.  My npm account is binkydog242.

**Comment by joshmanders** [comment]
Done and done. If you need any guidance let me know. You have full control over publishing and this repo, so if you want to change things up, go ahead.

**Comment by binkydog** [comment]
@joshmanders tried to push a branch to repo and got denied still.  Also I shot you and email, I need to fix the yarn.lock on this.

**Pull request merged**
