### PR TITLE
v2.4.2

### PR DESCRIPTION
**Pull request by n3il**
This PR is to update the repo to take the latest changes in https://github.com/doabit/semantic-ui-sass, which is at `2.4.2` now.

Commit https://github.com/aniftyco/semantic-ui-sass/commit/0e52f8a is the result of `yarn build`.
I then updated `package.json` to reflect the change.

### CODE REVIEW

**Review by binkydog — COMMENTED** [review]
Hi @n3il.  I think this is all good.  Before I approve, would you mind tagging this is "2.4.2" so when we publish it will jive with your package.json version.  Thanks

**Comment by n3il** [comment]
@binkydog I'm not sure I understand. Are you referring to the latest commit message?

**Comment by n3il** [comment]
@binkydog Tagged 👍 

I realize you're referring to git tags now (of course).

**Comment by n3il** [comment]
bump 😄 

can this get merged now?

**Comment by binkydog** [comment]
Merged and published to npm!  Thanks for contributing.

**Pull request merged**
